-- Add indexes for foreign keys and remove unused indexes

-- Ensure foreign keys have supporting indexes
CREATE INDEX IF NOT EXISTS idx_bot_users_current_plan_id ON bot_users (current_plan_id);
CREATE INDEX IF NOT EXISTS idx_channel_memberships_added_by ON channel_memberships (added_by);
CREATE INDEX IF NOT EXISTS idx_channel_memberships_package_id ON channel_memberships (package_id);
CREATE INDEX IF NOT EXISTS idx_user_package_assignments_assigned_by ON user_package_assignments (assigned_by);

-- Drop unused indexes
DROP INDEX IF EXISTS idx_subscription_plans_active;
DROP INDEX IF EXISTS idx_payments_status;
DROP INDEX IF EXISTS idx_payments_user_plan;
DROP INDEX IF EXISTS idx_payments_user_status;
DROP INDEX IF EXISTS idx_payment_analytics;
DROP INDEX IF EXISTS idx_payments_plan_id;
DROP INDEX IF EXISTS idx_payments_user_id;
DROP INDEX IF EXISTS idx_payments_status_created;
DROP INDEX IF EXISTS idx_payments_user_status_date;
DROP INDEX IF EXISTS idx_user_surveys_completed_at;
DROP INDEX IF EXISTS idx_media_files_uploaded_by;
DROP INDEX IF EXISTS idx_media_files_created_at;
DROP INDEX IF EXISTS idx_media_files_telegram_file_id;
DROP INDEX IF EXISTS idx_media_files_telegram_file;
DROP INDEX IF EXISTS idx_auto_reply_templates_active;
DROP INDEX IF EXISTS idx_user_subscriptions_telegram_user_id;
DROP INDEX IF EXISTS idx_user_subscriptions_active;
DROP INDEX IF EXISTS idx_user_subscriptions_user_status;
DROP INDEX IF EXISTS idx_user_subscriptions_active_lookup;
DROP INDEX IF EXISTS idx_user_subscriptions_plan_id;
DROP INDEX IF EXISTS idx_user_subscriptions_status_date;
DROP INDEX IF EXISTS idx_promotions_active_code;
DROP INDEX IF EXISTS idx_promotions_active;
DROP INDEX IF EXISTS idx_promotion_usage_promotion_id;
DROP INDEX IF EXISTS idx_daily_analytics_date;
DROP INDEX IF EXISTS idx_user_interactions_type;
DROP INDEX IF EXISTS idx_user_interactions_date;
DROP INDEX IF EXISTS idx_user_interactions_telegram_user_id;
DROP INDEX IF EXISTS idx_user_interactions_type_created;
DROP INDEX IF EXISTS idx_user_interactions_user_type_date;
DROP INDEX IF EXISTS idx_promo_analytics_created_at;
DROP INDEX IF EXISTS idx_promo_analytics_promo_code;
DROP INDEX IF EXISTS idx_education_packages_category_id;
DROP INDEX IF EXISTS idx_education_packages_active;
DROP INDEX IF EXISTS idx_education_enrollments_package_id;
DROP INDEX IF EXISTS idx_education_enrollments_telegram_user_id;
DROP INDEX IF EXISTS idx_education_enrollments_status;
DROP INDEX IF EXISTS idx_bot_users_admin_vip;
DROP INDEX IF EXISTS idx_bot_users_telegram_id_lookup;
DROP INDEX IF EXISTS idx_admin_stats_composite;
DROP INDEX IF EXISTS idx_bot_users_active_admin;
DROP INDEX IF EXISTS idx_bot_users_is_admin;
DROP INDEX IF EXISTS idx_bot_users_is_vip;
DROP INDEX IF EXISTS idx_bot_users_created_at;
DROP INDEX IF EXISTS idx_admin_logs_admin_telegram_id;
DROP INDEX IF EXISTS idx_admin_logs_created_at;
DROP INDEX IF EXISTS idx_admin_logs_action_type;
DROP INDEX IF EXISTS idx_bot_settings_key_active;
DROP INDEX IF EXISTS idx_bot_sessions_telegram_user_id;
DROP INDEX IF EXISTS idx_bot_sessions_session_start;
DROP INDEX IF EXISTS idx_bot_sessions_active;
DROP INDEX IF EXISTS idx_bot_sessions_user_active;
DROP INDEX IF EXISTS idx_bot_content_key_active;
DROP INDEX IF EXISTS idx_profiles_telegram_id;
DROP INDEX IF EXISTS idx_profiles_role;
DROP INDEX IF EXISTS idx_assignments_user_id;
DROP INDEX IF EXISTS idx_assignments_package_id;
DROP INDEX IF EXISTS idx_assignments_active;
DROP INDEX IF EXISTS idx_memberships_user_id;
DROP INDEX IF EXISTS idx_memberships_channel_id;
DROP INDEX IF EXISTS idx_memberships_telegram_user_id;
DROP INDEX IF EXISTS idx_broadcast_messages_status;
DROP INDEX IF EXISTS idx_broadcast_messages_scheduled;
DROP INDEX IF EXISTS idx_broadcast_messages_media_file_id;
